site_name: Style Guide
site_url: https://rthrbrs.github.io/styleguide/
nav:
  - Home: index.md
  - People: titles.md
  - Places: ToponymsAndEthnonyms.md
  - Numbers and Currencies: numbers.md
  - Polish Officials and Institutions: Poland.md
  - Translating from Polish: translating_from_Polish.md
  - Punctuation: Punctuation.md
  - Frequently (Mis)used Namestraps: Namestraps.md
  - NATO in Poland: NATO_PL.md
  - Polish Committees and Commissions: Committees.md
 # - Pronunciation: Pronunciation.md
 # - Banned Phrases: BannedPhrases.md
 # - Editorial Guidelines: EditorialGuidelines.md
 # - European Political Parties: EuropeanPoliticalParties.md

theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
