site_name: Style Guide
site_url: http://localhost:8000
nav:
  - Home: index.md
  - Banned Phrases: BannedPhrases.md
  - Editorial Guidelines: EditorialGuidelines.md
  - European Political Parties: EuropeanPoliticalParties.md
##- Frequently Used Namestraps: Namestraps.md
  - Geography: ToponymsAndEthnonyms.md
  - NATO in Poland: NATO_PL.md
  - Numbers and Currencies: numbers.md
  - Official Titles: titles.md
  - Polish Committees and Commissions: Committees.md
  - Polish Officials and Institutions: Poland.md
  - Pronunciation: Pronunciation.md
  - Punctuation: Punctuation.md
  - Translating from Polish: translating_from_Polish.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
